language: android
android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - sys-img-armeabi-v7a-android-25
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
